from dataclasses import dataclass

from rdflib import term
from rdflib.plugins.sparql.algebra import translateQuery
from rdflib.plugins.sparql.parser import parseQuery


@dataclass(frozen=True)
class BGP:
    body: str
    num_triples: int
    max_arity: int


QUERY_PATTERN_TEMPLATES: dict[str, BGP] = {
    "2p": BGP("?x1 ?r1 ?x2 . ?x2 ?r2 ?x3 .", num_triples=2, max_arity=2),
    "2i": BGP("?x1 ?r1 ?x3 . ?x2 ?r2 ?x3 .", num_triples=2, max_arity=2),
    "1p2i": BGP(
        "?x1 ?r1 ?x2 . ?x2 ?r2 ?x3 . ?x4 ?r3 ?x3 .", num_triples=3, max_arity=2
    ),
    "2i1p": BGP(
        "?x1 ?r1 ?x3 . ?x2 ?r2 ?x3 . ?x3 ?r3 ?x4 .", num_triples=3, max_arity=2
    ),
    "3p": BGP("?x1 ?r1 ?x2 . ?x2 ?r2 ?x3 . ?x3 ?r3 ?x4 .", num_triples=3, max_arity=2),
    "3i": BGP("?x1 ?r1 ?x4 . ?x2 ?r2 ?x4 . ?x3 ?r3 ?x4 .", num_triples=3, max_arity=3),
    "r-2i": BGP("?x1 ?r1 ?x2 . ?x1 ?r2 ?x3 .", num_triples=2, max_arity=2),
    "r-1p2i": BGP(
        "?x1 ?r1 ?x2 . ?x1 ?r2 ?x3 . ?x2 ?r3 ?x4 .", num_triples=3, max_arity=2
    ),
    "r-2i1p": BGP(
        "?x1 ?r1 ?x2 . ?x2 ?r2 ?x3 . ?x2 ?r3 ?x4 .", num_triples=3, max_arity=2
    ),
    "r-3i": BGP(
        "?x1 ?r1 ?x2 . ?x1 ?r2 ?x3 . ?x1 ?r3 ?x4 .", num_triples=3, max_arity=3
    ),
}


RDFTriple = tuple[term.Node, term.Node, term.Node]


def extract_triples_from_bgp(bgp: BGP) -> set[RDFTriple]:
    return extract_triples_from_bgp_body(bgp.body)


def extract_triples_from_bgp_body(bgp: str) -> set[RDFTriple]:
    """
    Extract subject-predicate-object triples from a SPARQL Basic Graph Pattern.

    Args:
        bgp: The BGP.

    Returns:
        A set of (subject, predicate, object) tuples

    Example:
        >>> bgp = "?person foaf:name ?name ; foaf:age ?age ."
        >>> triples = extract_triples_from_bgp(bgp)
    """
    # Wrap the BGP in a minimal SPARQL query structure
    sparql_query = f"""SELECT * WHERE {{ {bgp} }}"""

    # Parse the SPARQL query
    parsed = parseQuery(sparql_query)

    # Translate to query
    query = translateQuery(parsed)

    # Extract triples from the algebra tree
    triples = set()

    #
    # The following function has been generated by an LLM, but it has been tested quite deeply, and it seems to be correct
    #
    def extract_from_algebra(node):
        """Recursively extract triples from the algebra tree."""
        # The algebra structure is a dict-like object
        if isinstance(node, dict):
            # Look for 'triples' key which contains the BGP triples
            if "triples" in node:
                for triple in node["triples"]:
                    triples.add(tuple(triple))

            # Recursively search all values
            for value in node.values():
                if isinstance(value, (dict, list)):
                    extract_from_algebra(value)

        # Handle lists
        elif isinstance(node, list):
            for item in node:
                extract_from_algebra(item)

    extract_from_algebra(query.algebra)
    return triples


def extract_entities_predicates_from_bgp(
    bgp: BGP,
) -> tuple[set[term.Node], set[term.Node]]:
    triples = extract_triples_from_bgp(bgp)
    entities = set(t[0] for t in triples) | set(t[2] for t in triples)
    predicates = set(t[1] for t in triples)
    return entities, predicates
